# Generated by Django 3.1.7 on 2021-03-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Guest Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Guest E-mail')),
                ('booking_details', models.CharField(max_length=3000, verbose_name='Booking Details')),
                ('status', models.CharField(choices=[('0', 'Blocked'), ('1', 'Active')], default='Active', max_length=11, verbose_name='Satus')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
            ],
        ),
    ]
